version: "3.9"
services:
    mongodb:
        image: mongo
        container_name: my-mongodb
        ports:
            - 27017:27017
        volumes:
            - data:/data
        environment:
            - MONGO_INITDB_ROOT_USERNAME=rootuser
            - MONGO_INITDB_ROOT_PASSWORD=rootpass
    mongo-express:
        image: mongo-express
        container_name: my-mongo-express
        restart: always
        ports:
            - 8082:8082
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
            - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
            - ME_CONFIG_MONGODB_SERVER=mongodb
    app:
        image: tea-time
        container_name: my-tea-time
        environment:
            - MONGO_HOST=mongodb
            - MONGO_PORT=27017
            - MONGO_USERNAME=rootuser
            - MONGO_PASSWORD=rootpass
            - MONGO_DATABASE=tea_time
        ports:
            - "127.0.0.1:80:8081"
        depends_on:
            - mongodb
volumes:
    data: {}
networks:
    default:
        name: mongodb_network